//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/marciohenrique/Downloads/uenp/TF_Compiladores-main/LangC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  namespace LangC.Grammar;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILangCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LangCBaseListener : ILangCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangCParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] LangCParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangCParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] LangCParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>includeDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeDirective([NotNull] LangCParser.IncludeDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>includeDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeDirective([NotNull] LangCParser.IncludeDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>defineDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineDirective([NotNull] LangCParser.DefineDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>defineDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineDirective([NotNull] LangCParser.DefineDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mainFunctionBlock</c>
	/// labeled alternative in <see cref="LangCParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainFunctionBlock([NotNull] LangCParser.MainFunctionBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mainFunctionBlock</c>
	/// labeled alternative in <see cref="LangCParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainFunctionBlock([NotNull] LangCParser.MainFunctionBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnWithReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnWithReturn([NotNull] LangCParser.FnWithReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnWithReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnWithReturn([NotNull] LangCParser.FnWithReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnWithoutReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnWithoutReturn([NotNull] LangCParser.FnWithoutReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnWithoutReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnWithoutReturn([NotNull] LangCParser.FnWithoutReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] LangCParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] LangCParser.LineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistenteString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelExistenteString([NotNull] LangCParser.VariavelExistenteStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistenteString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelExistenteString([NotNull] LangCParser.VariavelExistenteStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelNovaString([NotNull] LangCParser.VariavelNovaStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelNovaString([NotNull] LangCParser.VariavelNovaStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNova</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelNova([NotNull] LangCParser.VariavelNovaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNova</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelNova([NotNull] LangCParser.VariavelNovaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaFuncao</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelNovaFuncao([NotNull] LangCParser.VariavelNovaFuncaoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaFuncao</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelNovaFuncao([NotNull] LangCParser.VariavelNovaFuncaoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelNovaBoolean([NotNull] LangCParser.VariavelNovaBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelNovaBoolean([NotNull] LangCParser.VariavelNovaBooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistente</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelExistente([NotNull] LangCParser.VariavelExistenteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistente</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelExistente([NotNull] LangCParser.VariavelExistenteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistenteBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariavelExistenteBoolean([NotNull] LangCParser.VariavelExistenteBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistenteBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariavelExistenteBoolean([NotNull] LangCParser.VariavelExistenteBooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>inputVar</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputVar([NotNull] LangCParser.InputVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inputVar</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputVar([NotNull] LangCParser.InputVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>inputStr</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputStr([NotNull] LangCParser.InputStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inputStr</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputStr([NotNull] LangCParser.InputStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputStr([NotNull] LangCParser.OutputStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputStr([NotNull] LangCParser.OutputStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputVar([NotNull] LangCParser.OutputVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputVar([NotNull] LangCParser.OutputVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputExpr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputExpr([NotNull] LangCParser.OutputExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputExpr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputExpr([NotNull] LangCParser.OutputExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStrVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputStrVar([NotNull] LangCParser.OutputStrVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStrVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputStrVar([NotNull] LangCParser.OutputStrVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStrLine</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputStrLine([NotNull] LangCParser.OutputStrLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStrLine</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputStrLine([NotNull] LangCParser.OutputStrLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprSum</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprSum([NotNull] LangCParser.ExprSumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprSum</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprSum([NotNull] LangCParser.ExprSumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprSub</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprSub([NotNull] LangCParser.ExprSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprSub</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprSub([NotNull] LangCParser.ExprSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprTerm([NotNull] LangCParser.ExprTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprTerm([NotNull] LangCParser.ExprTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermMult([NotNull] LangCParser.TermMultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermMult([NotNull] LangCParser.TermMultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermDiv([NotNull] LangCParser.TermDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermDiv([NotNull] LangCParser.TermDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termMod</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermMod([NotNull] LangCParser.TermModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termMod</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermMod([NotNull] LangCParser.TermModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermFactor([NotNull] LangCParser.TermFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermFactor([NotNull] LangCParser.TermFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorExpr([NotNull] LangCParser.FactorExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorExpr([NotNull] LangCParser.FactorExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorVar([NotNull] LangCParser.FactorVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorVar([NotNull] LangCParser.FactorVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNumD</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorNumD([NotNull] LangCParser.FactorNumDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNumD</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorNumD([NotNull] LangCParser.FactorNumDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorNum([NotNull] LangCParser.FactorNumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorNum([NotNull] LangCParser.FactorNumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorStr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorStr([NotNull] LangCParser.FactorStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorStr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorStr([NotNull] LangCParser.FactorStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfBlock([NotNull] LangCParser.IfBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfBlock([NotNull] LangCParser.IfBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifElseBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfElseBlock([NotNull] LangCParser.IfElseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifElseBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfElseBlock([NotNull] LangCParser.IfElseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>loopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopBlock([NotNull] LangCParser.LoopBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>loopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopBlock([NotNull] LangCParser.LoopBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forLoopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoopBlock([NotNull] LangCParser.ForLoopBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forLoopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoopBlock([NotNull] LangCParser.ForLoopBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>doWhileBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileBlock([NotNull] LangCParser.DoWhileBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>doWhileBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileBlock([NotNull] LangCParser.DoWhileBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="LangCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockLine([NotNull] LangCParser.BlockLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="LangCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockLine([NotNull] LangCParser.BlockLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="LangCParser.rblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBlockLine([NotNull] LangCParser.FnBlockLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="LangCParser.rblock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBlockLine([NotNull] LangCParser.FnBlockLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBodyLine([NotNull] LangCParser.FnBodyLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBodyLine([NotNull] LangCParser.FnBodyLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBodyLineMore([NotNull] LangCParser.FnBodyLineMoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBodyLineMore([NotNull] LangCParser.FnBodyLineMoreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnBoolLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnBoolLine([NotNull] LangCParser.FnReturnBoolLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnBoolLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnBoolLine([NotNull] LangCParser.FnReturnBoolLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnStrLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnStrLine([NotNull] LangCParser.FnReturnStrLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnStrLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnStrLine([NotNull] LangCParser.FnReturnStrLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnExprLine([NotNull] LangCParser.FnReturnExprLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnExprLine([NotNull] LangCParser.FnReturnExprLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnLine([NotNull] LangCParser.FnReturnLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnLine([NotNull] LangCParser.FnReturnLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprNot</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexprNot([NotNull] LangCParser.BexprNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprNot</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexprNot([NotNull] LangCParser.BexprNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprOr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexprOr([NotNull] LangCParser.BexprOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprOr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexprOr([NotNull] LangCParser.BexprOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprExpr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexprExpr([NotNull] LangCParser.BexprExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprExpr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexprExpr([NotNull] LangCParser.BexprExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprRelop</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexprRelop([NotNull] LangCParser.BexprRelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprRelop</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexprRelop([NotNull] LangCParser.BexprRelopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprAnd</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexprAnd([NotNull] LangCParser.BexprAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprAnd</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexprAnd([NotNull] LangCParser.BexprAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>uniqueParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniqueParam([NotNull] LangCParser.UniqueParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>uniqueParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniqueParam([NotNull] LangCParser.UniqueParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multipleParams</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultipleParams([NotNull] LangCParser.MultipleParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multipleParams</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultipleParams([NotNull] LangCParser.MultipleParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>noneParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneParam([NotNull] LangCParser.NoneParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>noneParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneParam([NotNull] LangCParser.NoneParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>uniqueParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniqueParamCall([NotNull] LangCParser.UniqueParamCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>uniqueParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniqueParamCall([NotNull] LangCParser.UniqueParamCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multipleParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultipleParamCall([NotNull] LangCParser.MultipleParamCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multipleParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultipleParamCall([NotNull] LangCParser.MultipleParamCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>noneParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneParamCall([NotNull] LangCParser.NoneParamCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>noneParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneParamCall([NotNull] LangCParser.NoneParamCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcInvoc</c>
	/// labeled alternative in <see cref="LangCParser.callFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncInvoc([NotNull] LangCParser.FuncInvocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcInvoc</c>
	/// labeled alternative in <see cref="LangCParser.callFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncInvoc([NotNull] LangCParser.FuncInvocContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
