//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/marciohenrique/Downloads/uenp/TF_Compiladores-main/LangC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


  namespace LangC.Grammar;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LangCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILangCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangCParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] LangCParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangCParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] LangCParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>includeDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeDirective([NotNull] LangCParser.IncludeDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>includeDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeDirective([NotNull] LangCParser.IncludeDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>defineDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineDirective([NotNull] LangCParser.DefineDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>defineDirective</c>
	/// labeled alternative in <see cref="LangCParser.preprocessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineDirective([NotNull] LangCParser.DefineDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mainFunctionBlock</c>
	/// labeled alternative in <see cref="LangCParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainFunctionBlock([NotNull] LangCParser.MainFunctionBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mainFunctionBlock</c>
	/// labeled alternative in <see cref="LangCParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainFunctionBlock([NotNull] LangCParser.MainFunctionBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnWithReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnWithReturn([NotNull] LangCParser.FnWithReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnWithReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnWithReturn([NotNull] LangCParser.FnWithReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnWithoutReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnWithoutReturn([NotNull] LangCParser.FnWithoutReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnWithoutReturn</c>
	/// labeled alternative in <see cref="LangCParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnWithoutReturn([NotNull] LangCParser.FnWithoutReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LangCParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] LangCParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LangCParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] LangCParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistenteString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelExistenteString([NotNull] LangCParser.VariavelExistenteStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistenteString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelExistenteString([NotNull] LangCParser.VariavelExistenteStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelNovaString([NotNull] LangCParser.VariavelNovaStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaString</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelNovaString([NotNull] LangCParser.VariavelNovaStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNova</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelNova([NotNull] LangCParser.VariavelNovaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNova</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelNova([NotNull] LangCParser.VariavelNovaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaFuncao</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelNovaFuncao([NotNull] LangCParser.VariavelNovaFuncaoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaFuncao</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelNovaFuncao([NotNull] LangCParser.VariavelNovaFuncaoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelNovaBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelNovaBoolean([NotNull] LangCParser.VariavelNovaBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelNovaBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelNovaBoolean([NotNull] LangCParser.VariavelNovaBooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistente</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelExistente([NotNull] LangCParser.VariavelExistenteContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistente</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelExistente([NotNull] LangCParser.VariavelExistenteContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariavelExistenteBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariavelExistenteBoolean([NotNull] LangCParser.VariavelExistenteBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariavelExistenteBoolean</c>
	/// labeled alternative in <see cref="LangCParser.atrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariavelExistenteBoolean([NotNull] LangCParser.VariavelExistenteBooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inputVar</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputVar([NotNull] LangCParser.InputVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inputVar</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputVar([NotNull] LangCParser.InputVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inputStr</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputStr([NotNull] LangCParser.InputStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inputStr</c>
	/// labeled alternative in <see cref="LangCParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputStr([NotNull] LangCParser.InputStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputStr([NotNull] LangCParser.OutputStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputStr([NotNull] LangCParser.OutputStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputVar([NotNull] LangCParser.OutputVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputVar([NotNull] LangCParser.OutputVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputExpr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputExpr([NotNull] LangCParser.OutputExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputExpr</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputExpr([NotNull] LangCParser.OutputExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStrVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputStrVar([NotNull] LangCParser.OutputStrVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStrVar</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputStrVar([NotNull] LangCParser.OutputStrVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>outputStrLine</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputStrLine([NotNull] LangCParser.OutputStrLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>outputStrLine</c>
	/// labeled alternative in <see cref="LangCParser.output"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputStrLine([NotNull] LangCParser.OutputStrLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprSum</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprSum([NotNull] LangCParser.ExprSumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprSum</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprSum([NotNull] LangCParser.ExprSumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprSub</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprSub([NotNull] LangCParser.ExprSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprSub</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprSub([NotNull] LangCParser.ExprSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprTerm([NotNull] LangCParser.ExprTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="LangCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprTerm([NotNull] LangCParser.ExprTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermMult([NotNull] LangCParser.TermMultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermMult([NotNull] LangCParser.TermMultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermDiv([NotNull] LangCParser.TermDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermDiv([NotNull] LangCParser.TermDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termMod</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermMod([NotNull] LangCParser.TermModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termMod</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermMod([NotNull] LangCParser.TermModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermFactor([NotNull] LangCParser.TermFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="LangCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermFactor([NotNull] LangCParser.TermFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorExpr([NotNull] LangCParser.FactorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorExpr([NotNull] LangCParser.FactorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorVar([NotNull] LangCParser.FactorVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorVar([NotNull] LangCParser.FactorVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNumD</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorNumD([NotNull] LangCParser.FactorNumDContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNumD</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorNumD([NotNull] LangCParser.FactorNumDContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorNum([NotNull] LangCParser.FactorNumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorNum([NotNull] LangCParser.FactorNumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factorStr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorStr([NotNull] LangCParser.FactorStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factorStr</c>
	/// labeled alternative in <see cref="LangCParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorStr([NotNull] LangCParser.FactorStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] LangCParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] LangCParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ifElseBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseBlock([NotNull] LangCParser.IfElseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifElseBlock</c>
	/// labeled alternative in <see cref="LangCParser.controlflow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseBlock([NotNull] LangCParser.IfElseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>loopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopBlock([NotNull] LangCParser.LoopBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>loopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopBlock([NotNull] LangCParser.LoopBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>forLoopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoopBlock([NotNull] LangCParser.ForLoopBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forLoopBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoopBlock([NotNull] LangCParser.ForLoopBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>doWhileBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileBlock([NotNull] LangCParser.DoWhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>doWhileBlock</c>
	/// labeled alternative in <see cref="LangCParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileBlock([NotNull] LangCParser.DoWhileBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="LangCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockLine([NotNull] LangCParser.BlockLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="LangCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockLine([NotNull] LangCParser.BlockLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="LangCParser.rblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBlockLine([NotNull] LangCParser.FnBlockLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="LangCParser.rblock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBlockLine([NotNull] LangCParser.FnBlockLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBodyLine([NotNull] LangCParser.FnBodyLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBodyLine([NotNull] LangCParser.FnBodyLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnBodyLineMore([NotNull] LangCParser.FnBodyLineMoreContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnBodyLineMore([NotNull] LangCParser.FnBodyLineMoreContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnBoolLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnBoolLine([NotNull] LangCParser.FnReturnBoolLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnBoolLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnBoolLine([NotNull] LangCParser.FnReturnBoolLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnStrLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnStrLine([NotNull] LangCParser.FnReturnStrLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnStrLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnStrLine([NotNull] LangCParser.FnReturnStrLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnExprLine([NotNull] LangCParser.FnReturnExprLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnExprLine([NotNull] LangCParser.FnReturnExprLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnReturnLine([NotNull] LangCParser.FnReturnLineContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="LangCParser.rbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnReturnLine([NotNull] LangCParser.FnReturnLineContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprNot</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexprNot([NotNull] LangCParser.BexprNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprNot</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexprNot([NotNull] LangCParser.BexprNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprOr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexprOr([NotNull] LangCParser.BexprOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprOr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexprOr([NotNull] LangCParser.BexprOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprExpr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexprExpr([NotNull] LangCParser.BexprExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprExpr</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexprExpr([NotNull] LangCParser.BexprExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprRelop</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexprRelop([NotNull] LangCParser.BexprRelopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprRelop</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexprRelop([NotNull] LangCParser.BexprRelopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bexprAnd</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexprAnd([NotNull] LangCParser.BexprAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bexprAnd</c>
	/// labeled alternative in <see cref="LangCParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexprAnd([NotNull] LangCParser.BexprAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>uniqueParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUniqueParam([NotNull] LangCParser.UniqueParamContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>uniqueParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUniqueParam([NotNull] LangCParser.UniqueParamContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multipleParams</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultipleParams([NotNull] LangCParser.MultipleParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multipleParams</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultipleParams([NotNull] LangCParser.MultipleParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>noneParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneParam([NotNull] LangCParser.NoneParamContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>noneParam</c>
	/// labeled alternative in <see cref="LangCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneParam([NotNull] LangCParser.NoneParamContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>uniqueParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUniqueParamCall([NotNull] LangCParser.UniqueParamCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>uniqueParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUniqueParamCall([NotNull] LangCParser.UniqueParamCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multipleParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultipleParamCall([NotNull] LangCParser.MultipleParamCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multipleParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultipleParamCall([NotNull] LangCParser.MultipleParamCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>noneParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneParamCall([NotNull] LangCParser.NoneParamCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>noneParamCall</c>
	/// labeled alternative in <see cref="LangCParser.paramsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneParamCall([NotNull] LangCParser.NoneParamCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>funcInvoc</c>
	/// labeled alternative in <see cref="LangCParser.callFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncInvoc([NotNull] LangCParser.FuncInvocContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcInvoc</c>
	/// labeled alternative in <see cref="LangCParser.callFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncInvoc([NotNull] LangCParser.FuncInvocContext context);
}
